### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by hara0510** [hara0510/furima-39494#22]
* 自身のフリマアプリのURL
https://furima-39494.onrender.com/

* Basic認証のIDとパスワード
ID:user
パスワード:pass

* 出品者用のメールアドレスとパスワード
ユーザー1 furima太郎
　メールアドレス:test1@com
　パスワード:password1

* 購入者用のメールアドレスとパスワード
ユーザー2 furima花子
　メールアドレス:test2@com
　パスワード:password2

**Comment by shodai-ito** [comment]
@hara0510 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [ ] **入力された販売価格によって、販売手数料や販売利益が変わること(JavaScriptを使用して実装すること)**
金額の表示はされますが、手数料と利益の合計が価格と一致しません。
一致するよう実装しましょう。
<img width="613" alt="スクリーンショット 2023-10-29 14 43 32" src="https://github.com/hara0510/furima-39494/assets/62537107/cc90e0d9-5c98-449a-98cd-2a2504c24706">

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by hara0510** [comment]
修正しました。

**Comment by shodai-ito** [comment]
@hara0510 さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
